# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Scan App

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'adopt'
        cache: maven
      
    - name: Build with Maven
      run: mvn clean package

    - name: Sonatype Lifecycle SCA Scan
      id: evaluate
      uses: sonatype/actions/evaluate@v1
      with:
        iq-server-url: https://iq.aplattel.ngrok.io/
        username: admin
        password: admin!23
        application-id: Github-SCA
        stage: "build"
        scan-targets: .
        upload-sarif-file: true

    - name: Save Sonatype SBOM
      if: steps.evaluate.outputs.scan-id
      uses: sonatype/actions/fetch-sbom@v1
      with:
        iq-server-url: https://iq.aplattel.ngrok.io/
        username: admin
        password: admin!23
        application-id: Github-SCA
        scan-id: ${{ steps.evaluate.outputs.scan-id }}
        sbom-standard: spdx
        sbom-version: 2.3
        artifact-name: sonatype-bom

    # - name: Upload Struts WAR
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: target
    #     path: target/struts2-rest-showcase.war

    # - name: Run Fortify SSC SAST Scan
    #   if: always()
    #   uses: fortify/github-action@v1
    #   with:
    #     sast-scan: true
    #     debricked-sca-scan: false
    #   env:
    #     SSC_URL: https://repo.aplattel.ngrok.io
    #     SSC_TOKEN: ${{secrets.SSC_TOKEN}}
    #     SC_SAST_TOKEN: ${{secrets.SC_SAST_CLIENT_AUTH_TOKEN}}
    #     SSC_APPVERSION: GitHub-SCA:struts
      
